### ISSUE TITLE
Nice to have: add transition effect to modal

### ISSUE THREAD

**Issue by Shawnxkwang** [geist-org/react#360]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - Like this https://material-ui.com/components/modal/#TransitionsModal.js

### Examples

```jsx
see above link
```

**Comment by unix** [comment]
This feature looks good and can be used in multiple components, the premise is that we have to abstract multiple animations.

Although there is no such big change plan now, I will consider trying to add it in the next major release. I need to break this feature down into more detailed features, because it may involve refactoring animation components. Later, I'll create some new issues to link to this feature.

**Comment by unix** [comment]
Anyone who has ideas about animation components or animation modules can leave your opinion here.
