### ISSUE TITLE
Error after setting type as submit in Modal.Action

### ISSUE THREAD

**Issue by leopku** [geist-org/react#383]
# Bug report 🐞

## Version & Environment

  - Version of browser
Chrome 85
  - Version of `geist-ui/react`
2.0.2

## Actual results (or Errors)

I got an error:

```
TypeScript error in ../src/components/ProjectCard.tsx(178,43):
Type '"submit"' is not assignable to type '"error" | "default" | "secondary" | "success" | "warning" | "abort" | "secondary-light" | "success-light" | "warning-light" | "error-light" | undefined'.  TS2322

    176 |               Cancel
    177 |             </Modal.Action>
  > 178 |             <Modal.Action form="msg_form" type="submit">Submit</Modal.Action>
```

**Comment by heyAyushh** [comment]
The type here you are writing is for action.

"type" here the library is based for themes, idk if type"submit" is needed here.

**Comment by unix** [comment]
If you want to use **native props** `type` on the `Modal.Action`,  please use `htmlType` instead of it.

```jsx
<Modal.Action form="msg_form" htmlType="submit">Submit</Modal.Action>
```

Component `Modal.Action` inherits from component `Button`, we can see from the [document](https://react.geist-ui.dev/en-us/components/button) of `Button` that `htmlType` is the alias of the native property.

**Comment by leopku** [comment]
``
