### ISSUE TITLE
Feat: useSystemTheme() hook

### ISSUE THREAD

**Issue by VaibhavAcharya** [geist-org/react#408]
# Feature request 🚀

  - [x] I will create Pull Request
  - [x] It's just a suggestion

### Expected

  - A hook which gives the value of theme preferred by user in system.
  - This could be pretty handy for creating theme selection menus.
  - Hook will either return 'light' or 'dark'.
  - To make it compatible with SSR we could just return a default theme specified by user.

### Examples

Vercel theme menu:
![VercelThemeMenu](https://user-images.githubusercontent.com/41478382/97275254-b4d6d200-185b-11eb-9436-aac7cb350fbf.png)

### Others (Optional)
Although I could create a PR for this hook but we can also use an existing [one](https://github.com/xcv58/use-system-theme/).
I have no problem with either of it. 🙌

**Comment by unix** [comment]
If this hook (`useSystemTheme`) is used, there is an issue of conflict between the theme and the SSR here:

  - If the default theme is `dark`, then the background of the page must be black (`#000`).

  - The page is the default when SSR returns, just the default white `body`.

So, this way the user will see white the moment the page renders, even if they set the default `dark theme`. Unless, we set the default page `background-color` in a blocking manner before the browser renders it.

----

Here is how the browser renders the page, **please note that the `theme` is set after the initial rendering of the page**:

  1. The browser gets the HTML string returned by SSR and starts rendering.

  2. In the default HTML string, the `background-color` of the page is not set. (`#fff`)

  3. The browser renders the basic page structure.

  4. The browser starts parsing the hooks and then gets the settings on the `client side`, such as the `system-vars` / `client API` / `localStorage` etc.

  5. `useEffect` triggers a page re-render with a black background.

The problem here is that `hooks`, or any code that runs within `useEffect`, can only be updated after the browser's initial rendering is complete, this causes the page to have a short flickering white background.

----
**Summary**: 
Changing the default `background-color` using only `hooks` may result in a `second rendering` to change it.

And, I'd like to hear your perspective on the issue. (That's the key to whether or not `useSystemTheme` actually works.)

References:
  - [document.jsx](https://github.com/unix/unix.bio/blob/template/pages/_document.jsx) I encountered this problem on my blog as well, and then I chose to add a blocking run script to resolve the issue.

**Comment by unix** [comment]
Of course, telling users in our documentation *how they should set the default `background-color`* is one of the solutions, but it's not the best way to do it!

**Comment by VaibhavAcharya** [comment]
This is the nature of SSR so we cannot do much about it. We will have to choose either flicker or blocking script.
Personally, a flicker will be better than blocking script and forcing dev to implement correct bg-color separately .

Just to add to discussion Vercel website does it the blocking script way:
![VercelThemeBlockingScript](https://user-images.githubusercontent.com/41478382/97308525-f6c93d80-1886-11eb-877c-ea0aee66faef.PNG)

This choice is up to you or perhaps a poll can be created.

**Comment by arguiot** [comment]
If you're using NextJS, in you `_app.js` file you can use the following code:
```js
const [themeType, setThemeType] = React.useState('light')
React.useEffect(() => {
	const md = window.matchMedia('(prefers-color-scheme: dark)')
	setThemeType(lastThemeType => (md.matches ? 'dark' : 'light'))

	const handler = event => {
		setThemeType(lastThemeType => (event.matches ? 'dark' : 'light'))
	}

	try {
		// Chrome & Firefox
		md.addEventListener('change', handler);
	} catch (e1) {
		try {
			// Safari
			md.addListener(handler);
		} catch (e2) {
			console.error(e2);
		}
	}
}, [])
// ...
return <GeistProvider theme={{ type: themeType }}>
```

**Comment by unix** [comment]
@VaibhavAcharya 
The hook could be an external feature on its own, but it does seem to be useful. And if you'd like to add some explanatory notes to the documentation for this feature, I think this feature could be added.

**Comment by VaibhavAcharya** [comment]
Maybe with delay but I could surely create docs for the hook. Should I start working?

**Comment by 10000multiplier** [comment]
@arguiot your snippet isn't working for me 🤷‍♂️
