### ISSUE TITLE
NextJS 10 Image component support

### ISSUE THREAD

**Issue by arguiot** [geist-org/react#409]
# Feature request 🚀

  - [ ] I will create Pull Request
  - [x] It's just a suggestion

### Expected

Since version 10.0.0 Next.js has a built-in Image Component and Automatic Image Optimization.

The Automatic Image Optimization allows for resizing, optimizing, and serving images in modern formats like WebP. This avoids shipping large images to devices with a smaller viewport.

Since the Next.js Image Component (next/image) is an extension of the HTML `<img>` element, it would be very easy to replace the current `<img>` element.

I understand that this component library is not only for Next but also for other React environment so this should be **optional**.

### Examples

```jsx
// From
<Image width={540} height={160} src="/images/custom-domains.png" />
// To
<Image optimized width={540} height={160} src="/images/custom-domains.png" />
// Or (if it's not possible to import the next/image component from Geist)
<Image component={ NextImage } width={540} height={160} src="/images/custom-domains.png" /> // Where NextImage is next/image
```

**Comment by unix** [comment]
This feature will be on hold for a while, unless there is a better way to implement it. There are some problems at present:

1. `next/image` will replace the DOM, which may cause some image dependent layout styles to change (some styles may be jittery). Sure, it can be fixed here, but the way it currently works (or the way it was designed) is not good.

2. Components that use `as={Component}` syntax can be type-bound, but smart hints in the editor can be very slow, this is because the component's props type is dynamically derived, and the development experience here is poor.
