### ISSUE TITLE
Rollup and modern tooling compatibility

### ISSUE THREAD

**Issue by danchitnis** [geist-org/react#413]
# Bug report 🐞

Geist doesn't work with Rollup, and modern tooling like Snowpack, due to problems in [styled-jsx](https://github.com/vercel/styled-jsx) specifically mentioned [here](https://github.com/vercel/styled-jsx/issues/669) and [here](https://github.com/vercel/styled-jsx/issues/588). 

This is a great UI library, but that the fact that it can only run with Webpack is defeating the purpose of minimalistic and modern ESM compatibility that this library can offer. Is using [styled-jsx](https://github.com/vercel/styled-jsx) essential for this library? It doesn't seem very well maintained.

## Version & Environment

  - [Rollup](https://rollupjs.org/) and [Snowpack](https://www.snowpack.dev/)

## Expection

The behavior I expect is to get bundled without bugs.

## Actual results (or Errors)

I got an error: [here](https://github.com/vercel/styled-jsx/issues/669) and [here](https://github.com/vercel/styled-jsx/issues/588).

**Comment by unix** [comment]
**About ESM:**
I tried to compile a bundle of `esm` using [babel](https://github.com/geist-org/react/blob/master/package.json#L39), it also seems to work if you need `esm` mode, but the output package is still not concise enough.

**About rollup:**
My initial thought was to wait for `rollup` to fix the issue and then I would follow up with an upgrade, now it seems that this problem still exists and has not been solved, which is a technology selection error. Due to a large amount of code that depends on `styled-jsx`, there is no easy way to move to other libraries yet.

I evaluated the workload of removing `styled-jsx` when I added the `esm` module, the simplest solution would require changes to each component, test case, and server-side rendering module, so, at least in version `2.x` I have not removed the idea of `styled-jsx`.

A sad conclusion 😢 , but the good thing is that users can still use `esm` bundle, it's just that it will be a bit larger than the best practice package. (I would guess that the volume of useless code is about 10% - 25%)

**Comment by unix** [comment]
For any new comments, please reopen it.
