### ISSUE TITLE
Page still has margins on mobile. Scale function is not very responsive

### ISSUE THREAD

**Issue by sannajammeh** [geist-org/react#587]
# Bug report 🐞

## Version & Environment

  - Version of browser - latest chrome
  - Version of `geist-ui/react` - 2.2.0

## Expected Behaviour
Margins should disappear on mobile. 

## Actual results (or Errors)

![image](https://user-images.githubusercontent.com/50969683/127186663-63b51b13-70c6-48d5-b4f5-02ccf8925831.png)

```
code
```

**Comment by unix** [comment]
The `scaleable` function is not fully automatic and the exact settings depend on the values you fill.
If you want to populate different values on mobile and desktop devices, try using a combination of `scaleable` and [useMediaQuery](https://react.geist-ui.dev/en-us/components/use-media-query).

Examples:

```tsx
const isXS = useMediaQuery('xs')
const padding = isXS ? '5%' : '10vw'

return <Page.Content padding={padding} />
```

**Comment by sannajammeh** [comment]
The issue seems to be unrelated to padding and margin. 

This is present on the main Page component's styling even on mobile.
```css
width: calc(100% - 100pt);
```
I must add this code every time I use the Page component in order for it to disappear:

```jsx
const isXS = useMediaQuery('xs')
return <Page width={isXS ? '100%' : undefined}>
```

The page width should be 100% on mobile and not calc(100% - 100pt) as default imo.

**Comment by sannajammeh** [comment]
This seems to cause another problem in SSR
```ts
 const isMobile = useMediaQuery('mobile', { ssrMatchMedia: () => ({ matches: true }) });
 return <Page width={isMobile ? '100%' : undefined}>
```

Produces:
`Warning: Prop className did not match. Server: "jsx-1441301357 " Client: "jsx-42076441 "`
on the Page component. And causes the page component to not provide the intended width.

**Comment by unix** [comment]
If you need to accomplish both of the following goals, then you must ensure that the zi'fu'c rendered on the server side and the client side are fully synchronized:
1. server-side render
2. use an API that only works on the client-side (e.g. `mediaQuery` `localStorage`)

This is because the server-side works in a different environment than the client-side when generating HTML strings, you can refer to the following solutions:

- Render without server-side
- Use server-side render, but delayed client-side rendering
- Emulate the client API on the server-side

----
### Refs

- [issue#258](https://github.com/geist-org/react/issues/258)
- [tips of uselayouteffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect)
